/*
 * This source file was generated by the Gradle 'init' task
 */
package testarknight;

import javax.swing.*;

import java.awt.*;

public class App extends JFrame {

    public App() {
        setTitle("Spotify");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1920, 1080);
        setLayout(new BorderLayout());
    
        JSplitPane splitPane = new JSplitPane();
        splitPane.setDividerLocation(240);
        splitPane.setBorder(null);
        splitPane.setLeftComponent(new Sidebar());
        splitPane.setRightComponent(new JPanel()); 
    
        add(new MenuItem("Honkai: Star Rail Characters List"), BorderLayout.NORTH);
        add(splitPane, BorderLayout.CENTER);
    }
    
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            new App().setVisible(true);
        });
    }
}
