/*
 * This source file was generated by the Gradle 'init' task
 */

package testarknight;

import java.awt.*;
import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicSplitPaneDivider;
import javax.swing.plaf.basic.BasicSplitPaneUI;

public class App extends JFrame {

    public App() {

        // Set website foundation
        setTitle("Honkai: Star Rail Characters");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1920, 1080);
        setLayout(new BorderLayout());
    
        // Make the Character grid scrollable and the scroll speed faster
        CharacterGrid charGrid = new CharacterGrid();
        JScrollPane scrollPane = new JScrollPane(charGrid);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.getVerticalScrollBar().setUnitIncrement(32);

        // Create a panel that can be resized by cursor
        JSplitPane splitPane = new JSplitPane();    
        splitPane.setDividerLocation(240);
        splitPane.setLeftComponent(new Sidebar());
        splitPane.setRightComponent(scrollPane); 
        splitPane.setDividerSize(10); // Make it 1 pixel thin

        // Custom UI to make it invisible
        splitPane.setUI(new BasicSplitPaneUI() {
            @Override
            public BasicSplitPaneDivider createDefaultDivider() {
                return new BasicSplitPaneDivider(this) {
                    @Override
                    public void setBorder(Border b) {
                        // No border
                    }

                    @Override
                    public void paint(Graphics g) {
                        // Don't draw anything—fully invisible
                    }
                };
            }
        });
    
        // Navbar on the top
        add(new Navbar(), BorderLayout.NORTH);
        add(splitPane, BorderLayout.CENTER);
    }
    
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            new App().setVisible(true);
        });
    }
}
