/*
 * This source file was generated by the Gradle 'init' task
 */

package testarknight;

import java.awt.*;
import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicSplitPaneDivider;
import javax.swing.plaf.basic.BasicSplitPaneUI;

public class App extends JFrame {

    public App() {

        // Set website foundation
        setTitle("Honkai: Star Rail Characters");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1536, 864);
        
        // Make the Character grid scrollable and the scroll speed faster
        CharacterGrid charGrid = new CharacterGrid();
        JScrollPane scrollPane = new JScrollPane(charGrid);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.getVerticalScrollBar().setUnitIncrement(32);
        scrollPane.getHorizontalScrollBar().setUnitIncrement(32);
        scrollPane.setBorder(null); // Remove ugly thin blue line around the panel grr

        // Create a panel that can be resized by cursor
        JSplitPane splitPane = new JSplitPane();    
        splitPane.setDividerLocation(240);
        splitPane.setLeftComponent(new Sidebar(splitPane));
        splitPane.setRightComponent(scrollPane);
        splitPane.setBorder(null); // Remove ugly thin blue line around the panel
    
        // Navbar on the top
        add(new Navbar(), BorderLayout.NORTH);
        add(splitPane, BorderLayout.CENTER);
    }
    
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            new App().setVisible(true);
        });
    }
}
