package testarknight;

import java.awt.*;
import javax.swing.*;

public class LightconeGrid extends JPanel {

    public LightconeGrid() {
        
        // Set grid foundation
        setLayout(new GridLayout(0, 4, 10, 10));
        setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 20));
        setBackground(Color.decode("#2D2D2D"));
        
        // Adding every single HSR Light Cone
        add(new LightconeCard("A Grounded Ascent", "/light_cones/A_Grounded_Ascent.png", "Harmony", 5));
        add(new LightconeCard("A Secret Vow", "/light_cones/A_Secret_Vow.png", "Destruction", 4));
        add(new LightconeCard("Adversarial", "/light_cones/Adversarial.png", "Hunt", 3));
        add(new LightconeCard("After the Charmony Fall", "/light_cones/After_the_Charmony_Fall.png", "Erudition", 4));
        add(new LightconeCard("Along the Passing Shore", "/light_cones/Along_the_Passing_Shore.png", "Nihility", 5));
        add(new LightconeCard("Amber", "/light_cones/Amber.png", "Preservation", 3));
        add(new LightconeCard("An Instant Before A Gaze", "/light_cones/An_Instant_Before_A_Gaze.png", "Erudition", 5));
        add(new LightconeCard("Arrows", "/light_cones/Arrows.png", "Hunt", 3));
        add(new LightconeCard("Baptism of Pure Thought", "/light_cones/Baptism_of_Pure_Thought.png", "Hunt", 5));
        add(new LightconeCard("Before Dawn", "/light_cones/Before_Dawn.png", "Erudition", 5));
        add(new LightconeCard("Before the Tutorial Mission Starts", "/light_cones/Before_the_Tutorial_Mission_Starts.png", "Nihility", 4));
        add(new LightconeCard("Boundless Choreo", "/light_cones/Boundless_Choreo.png", "Nihility", 4));
        add(new LightconeCard("Brigther_Than_the_Sun", "/light_cones/Brighter_Than_the_Sun.png", "Destruction", 5));
        add(new LightconeCard("But the Battle Isn't Over", "/light_cones/But_the_Battle_Isn't_Over.png", "Harmony", 5));
        add(new LightconeCard("Carve the Moon, Weave the Clouds", "/light_cones/Carve_the_Moon,_Weave_the_Clouds.png", "Harmony", 4));
        add(new LightconeCard("Chorus", "/light_cones/Chorus.png", "Harmony", 3));
        add(new LightconeCard("Collapsing Sky", "/light_cones/Collapsing_Sky.png", "Destruction", 3));
        add(new LightconeCard("Concert for Two", "/light_cones/Concert_for_Two.png", "Preservation", 4));
        add(new LightconeCard("Cornucopia", "/light_cones/Cornucopia.png", "Abundance", 3));
        add(new LightconeCard("Cruising in the Stellar Sea", "/light_cones/Cruising_in_the_Stellar_Sea.png", "Hunt", 5));
        add(new LightconeCard("Dance! Dance! Dance!", "/light_cones/Dance!_Dance!_Dance!.png", "Harmony", 4));
        add(new LightconeCard("Dance at Sunset", "/light_cones/Dance_at_Sunset.png", "Destruction", 5));
        add(new LightconeCard("Darting Arrow", "/light_cones/Darting_Arrow.png", "Hunt", 3));
        add(new LightconeCard("Data Bank", "/light_cones/Data_Bank.png", "Erudition", 3));
        add(new LightconeCard("Day One of My New Life", "/light_cones/Day_One_of_My_New_Life.png", "Preservation", 4));
        add(new LightconeCard("Defense", "/light_cones/Defense.png", "Preservation", 3));
        add(new LightconeCard("Destiny's Threads Forewoven", "/light_cones/Destiny's_Threads_Forewoven.png", "Preservation", 4));
        add(new LightconeCard("Dream's Montage", "/light_cones/Dream's_Montage.png", "Abundance", 4));
        add(new LightconeCard("Dreamville Adventure", "/light_cones/Dreamville_Adventure.png", "Harmony", 4));
        add(new LightconeCard("Earthly Escapade", "/light_cones/Earthly_Escapade.png", "Harmony", 5));
        add(new LightconeCard("Echoes of the Coffin", "/light_cones/Echoes_of_the_Coffin.png", "Abundance", 5));
        add(new LightconeCard("Eternal Calculus", "/light_cones/Eternal_Calculus.png", "Erudition", 5));
        add(new LightconeCard("Eyes of the Prey", "/light_cones/Eyes_of_the_Prey.png", "Nihility", 4));
        add(new LightconeCard("Fermata", "/light_cones/Fermata.png", "Nihility", 4));
        add(new LightconeCard("Final Victor", "/light_cones/Final_Victor.png", "Hunt", 4));
        add(new LightconeCard("Fine Fruit", "/light_cones/Fine_Fruit.png", "Abundance", 3));
        add(new LightconeCard("Flames Afar", "/light_cones/Flames_Afar.png", "Destruction", 4));
        add(new LightconeCard("Flame of Blood, Blaze My Path", "/light_cones/Flame_of_Blood,_Blaze_My_Path.png", "Destruction", 5));
        add(new LightconeCard("Flowing Nightglow", "/light_cones/Flowing_Nightglow.png", "Harmony", 5));
        add(new LightconeCard("For Tomorrow's Journey", "/light_cones/For_Tomorrow's_Journey.png", "Harmony", 4));
        add(new LightconeCard("Geniuses' Greetings", "/light_cones/Geniuses'_Greetings.png", "Remembrance", 4));
        add(new LightconeCard("Geniuses' Repose", "/light_cones/Geniuses'_Repose.png", "Erudition", 4));
        add(new LightconeCard("Good Night and Sleep Well", "/light_cones/Good_Night_and_Sleep_Well.png", "Nihility", 4));
        add(new LightconeCard("Hey, Over Here", "/light_cones/Hey,_Over_Here.png", "Abundance", 4));
        add(new LightconeCard("Hidden Shadow", "/light_cones/Hidden_Shadow.png", "Nihility", 3));
        add(new LightconeCard("I Shall Be My Own Sword", "/light_cones/I_Shall_Be_My_Own_Sword.png", "Destruction", 5));
        add(new LightconeCard("I Venture Forth to Hunt", "/light_cones/I_Venture_Forth_to_Hunt.png", "Hunt", 5));
        add(new LightconeCard("If Time Were a Flower", "/light_cones/If_Time_Were_a_Flower.png", "Harmony", 5));
        add(new LightconeCard("In the Name of the World", "/light_cones/In_the_Name_of_the_World.png", "Nihility", 5));
        add(new LightconeCard("In the Night", "/light_cones/In_the_Night.png", "Hunt", 5));
        add(new LightconeCard("Incessant Rain", "/light_cones/Incessant_Rain.png", "Nihility", 5));
        add(new LightconeCard("Indelible Promise", "/light_cones/Indelible_Promise.png", "Destruction", 4));
        add(new LightconeCard("Inherently Unjust Destiny", "/light_cones/Inherently_Unjust_Destiny.png", "Preservation", 5));
        add(new LightconeCard("Into the Unreachable Veil", "/light_cones/Into_the_Unreachable_Veil.png", "Erudition", 5));
        add(new LightconeCard("It's Showtime", "/light_cones/It's_Showtime.png", "Nihility", 4));
        add(new LightconeCard("Landau's Choice", "/light_cones/Landau's_Choice.png", "Preservation", 4));
        add(new LightconeCard("Life Should Be Cast to Flames", "/light_cones/Life_Should_Be_Cast_to_Flames.png", "Erudition", 5));
        add(new LightconeCard("Long Road Leads Home", "/light_cones/Long_Road_Leads_Home.png", "Nihility", 5));
        add(new LightconeCard("Loop", "/light_cones/Loop.png", "Nihility", 3));
        add(new LightconeCard("Make Farewells More Beautiful", "/light_cones/Make_Farewells_More_Beautiful.png", "Remembrance", 5));
        add(new LightconeCard("Make the World Clamor", "/light_cones/Make_the_World_Clamor.png", "Erudition", 4));
        add(new LightconeCard("Mediation", "/light_cones/Mediation.png", "Harmony", 3));
        add(new LightconeCard("Memories of the Past", "/light_cones/Memories_of_the_Past.png", "Preservation", 4));
        add(new LightconeCard("Memory's Curtain Never Falls", "/light_cones/Memory's_Curtain_Never_Falls.png", "Remembrance", 5));
        add(new LightconeCard("Meshing Cogs", "/light_cones/Meshing_Cogs.png", "Harmony", 3));
        add(new LightconeCard("Moment of Victory", "/light_cones/Moment_of_Victory.png", "Preservation", 5));
        add(new LightconeCard("Multiplication", "/light_cones/Multiplication.png", "Abundance", 3));
        add(new LightconeCard("Mutual Demise", "/light_cones/Mutual_Demise.png", "Destruction", 3));
        add(new LightconeCard("Night of Fright", "/light_cones/Night_of_Fright.png", "Abundance", 5));
        add(new LightconeCard("Night on the Milky Way", "/light_cones/Night_on_the_Milky_Way.png", "Erudition", 5));
        add(new LightconeCard("Ninja Record: Sound Hunt", "/light_cones/Ninja_Record_Sound_Hunt.png", "Destruction", 4));
        add(new LightconeCard("Ninjutsu Inscription: Dazzling Evilbreaker", "/light_cones/Ninjutsu_Inscription_Dazzling_Evilbreaker.png", "Erudition", 5));
        add(new LightconeCard("Nowhere to Run", "/light_cones/Nowhere_to_Run.png", "Destruction", 4));
        add(new LightconeCard("On the Fall of an Aeon", "/light_cones/On_the_Fall_of_an_Aeon.png", "Destruction", 5));
        add(new LightconeCard("Only Silence Remains", "/light_cones/Only_Silence_Remains.png", "Hunt", 4));
        add(new LightconeCard("Passkey", "/light_cones/Passkey.png", "Erudition", 3));
        add(new LightconeCard("Past and Future", "/light_cones/Past_and_Future.png", "Harmony", 4));
        add(new LightconeCard("Past Self in Mirror", "/light_cones/Past_Self_in_Mirror.png", "Harmony", 5));
        add(new LightconeCard("Patience Is All You Need", "/light_cones/Patience_Is_All_You_Need.png", "Nihility", 5));
        add(new LightconeCard("Perfect Timing", "/light_cones/Perfect_Timing.png", "Abundance", 4));
        add(new LightconeCard("Pioneering", "/light_cones/Pioneering.png", "Preservation", 3));
        add(new LightconeCard("Planetary Rendezvous", "/light_cones/Planetary_Rendezvous.png", "Harmony", 4));
        add(new LightconeCard("Poised to Bloom", "/light_cones/Poised_to_Bloom.png", "Harmony", 4));
        add(new LightconeCard("Post-Op Conversation", "/light_cones/Post-Op_Conversation.png", "Abundance", 4));
        add(new LightconeCard("Quid Pro Quo", "/light_cones/Quid_Pro_Quo.png", "Abundance", 4));
        add(new LightconeCard("Reforged Remembrance", "/light_cones/Reforged_Remembrance.png", "Nihility", 5));
        add(new LightconeCard("Reminiscence", "/light_cones/Reminiscence.png", "Remembrance", 3));
        add(new LightconeCard("Resolution Shines As Pearls of Sweat", "/light_cones/Resolution_Shines_As_Pearls_of_Sweat.png", "Nihility", 4));
        add(new LightconeCard("Return to Darkness", "/light_cones/Return_to_Darkness.png", "Hunt", 4));
        add(new LightconeCard("River Flows in Spring", "/light_cones/River_Flows_in_Spring.png", "Hunt", 4));
        add(new LightconeCard("Sagacity", "/light_cones/Sagacity.png", "Erudition", 3));
        add(new LightconeCard("Sailing Towards a Second Life", "/light_cones/Sailing_Towards_a_Second_Life.png", "Hunt", 5));
        add(new LightconeCard("Scent Alone Stays True", "/light_cones/Scent_Alone_Stays_True.png", "Abundance", 5));
        add(new LightconeCard("Shadowburn", "/light_cones/Shadowburn.png", "Remembrance", 3));
        add(new LightconeCard("Shadowed by Night", "/light_cones/Shadowed_by_Night.png", "Hunt", 4));
        add(new LightconeCard("Shared Feeling", "/light_cones/Shared_Feeling.png", "Abundance", 4));
        add(new LightconeCard("Shattered Home", "/light_cones/Shattered_Home.png", "Destruction", 3));
        add(new LightconeCard("She Already Shut Her Eyes", "/light_cones/She_Already_Shut_Her_Eyes.png", "Preservation", 5));
        add(new LightconeCard("Sleep Like the Dead", "/light_cones/Sleep_Like_the_Dead.png", "Hunt", 5));
        add(new LightconeCard("Solitary Healing", "/light_cones/Solitary_Healing.png", "Nihility", 5));
        add(new LightconeCard("Something Irreplaceable", "/light_cones/Something_Irreplaceable.png", "Destruction", 5));
        add(new LightconeCard("Subscribe for More!", "/light_cones/Subscribe_for_More!.png", "Hunt", 4));
        add(new LightconeCard("Sweat Now, Cry Less", "/light_cones/Sweat_Now,_Cry_Less.png", "Remembrance", 4));
        add(new LightconeCard("Swordplay", "/light_cones/Swordplay.png", "Hunt", 4));
        add(new LightconeCard("Texture of Memories", "/light_cones/Texture_of_Memories.png", "Preservation", 5));
        add(new LightconeCard("The Birth of the Self", "/light_cones/The_Birth_of_the_Self.png", "Erudition", 4));
        add(new LightconeCard("The Day The Cosmos Fell", "/light_cones/The_Day_The_Cosmos_Fell.png", "Erudition", 4));
        add(new LightconeCard("The Great Cosmic Enterprise", "/light_cones/The_Great_Cosmic_Enterprise.png", "Erudition", 4));
        add(new LightconeCard("The Moles Welcome You", "/light_cones/The_Moles_Welcome_You.png", "Destruction", 4));
        add(new LightconeCard("The Seriousness of Breakfast", "/light_cones/The_Seriousness_of_Breakfast.png", "Erudition", 4));
        add(new LightconeCard("The Unreachable Side", "/light_cones/The_Unreachable_Side.png", "Destruction", 5));
        add(new LightconeCard("This Is Me!", "/light_cones/This_Is_Me!.png", "Preservation", 4));
        add(new LightconeCard("Those Many Springs", "/light_cones/Those_Many_Springs.png", "Nihility",5));
        add(new LightconeCard("Time Waits for No One", "/light_cones/Time_Waits_for_No_One.png", "Abundance", 5));
        add(new LightconeCard("Time Woven Into Gold", "/light_cones/Time_Woven_Into_Gold.png", "Remembrance", 5));
        add(new LightconeCard("Today Is Another Peaceful Day", "/light_cones/Today_Is_Another_Peaceful_Day.png", "Erudition", 4));
        add(new LightconeCard("Trend of the Universal Market", "/light_cones/Trend_of_the_Universal_Market.png", "Preservation", 4));
        add(new LightconeCard("Under the Blue Sky", "/light_cones/Under_the_Blue_Sky.png", "Destruction", 4));
        add(new LightconeCard("Victory In a Blink", "/light_cones/Victory_In_a_Blink.png", "Remembrance", 4));
        add(new LightconeCard("Void", "/light_cones/Void.png", "Nihility", 3));
        add(new LightconeCard("Warmth Shortens Cold Nights", "/light_cones/Warmth_Shortens_Cold_Nights.png", "Abundance", 4));
        add(new LightconeCard("We Are Wildfire", "/light_cones/We_Are_Wildfire.png", "Preservation", 4));
        add(new LightconeCard("We Will Meet Again", "/light_cones/We_Will_Meet_Again.png", "Nihility", 4));
        add(new LightconeCard("What Is Real?", "/light_cones/What_Is_Real.png", "Abundance", 4));
        add(new LightconeCard("Whereabouts Should Dreams Rest", "/light_cones/Whereabouts_Should_Dreams_Rest.png", "Destruction", 5));
        add(new LightconeCard("Woof! Walk Time!", "/light_cones/Woof!_Walk_Time!.png", "Destruction", 4));
        add(new LightconeCard("Worrisome, Blissful", "/light_cones/Worrisome,_Blissful.png", "Hunt", 5));
        add(new LightconeCard("Yet Hope Is Priceless", "/light_cones/Yet_Hope_Is_Priceless.png", "Erudition", 5));
    }
}
